import type { Metadata } from "next"
import { Toaster } from "react-hot-toast"
import { ReduxProvider } from "@/providers/redux-provider"

import { SocketProvider } from "@/providers/socket-provider"
import { RouteGuard } from "@/components/layout/resource-guard"
import { AuthProvider } from "@/providers/auth-provider"
import { AppLayoutProvider } from "@/providers/app-layout-provider"

import "@/styles/index.scss"
import { NON_GUARD_ROUTES } from "@/utils/constants"

export const metadata: Metadata = {
   title: "Thunder Chat",
   description: "Generated by Code VCN",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang="en">
         <body className="bg-white text-white">
            <ReduxProvider>
               <AuthProvider>
                  <RouteGuard nonGuardRoutes={NON_GUARD_ROUTES}>
                     <SocketProvider>
                        <AppLayoutProvider>{children}</AppLayoutProvider>
                     </SocketProvider>
                  </RouteGuard>
               </AuthProvider>
            </ReduxProvider>

            <Toaster
               position="bottom-left"
               reverseOrder={true}
               toastOptions={{
                  duration: 3000,
                  error: {
                     style: {
                        fontWeight: "bold",
                     },
                  },
                  success: {
                     style: {
                        fontWeight: "bold",
                     },
                  },
               }}
            />
         </body>
      </html>
   )
}
