import type { Metadata } from "next"
import { Toaster } from "react-hot-toast"
import { ConfigProvider } from "antd"
import { CustomAntTheme } from "@/styles/antd.theme"
import { StyledComponentsRegistry } from "@/providers/antd-registry"
import { ReduxProvider } from "@/providers/redux-provider"

// config css for fontawesome
import { config } from "@fortawesome/fontawesome-svg-core"
import "@fortawesome/fontawesome-svg-core/styles.css"

import { SocketProvider } from "@/providers/socket-provider"
import { RouteGuard } from "@/components/resource.guard"
import { setNonGuardRoutes } from "@/utils/helpers"
import { AuthProvider } from "@/providers/auth-provider"
import { AppLayoutProvider } from "@/providers/app-layout-provider"
config.autoAddCss = false

// import my own css
import "@/styles/index.css"

export const metadata: Metadata = {
   title: "Thunder Chat",
   description: "Generated by Code VCN",
}

const nonGuardRoutes = setNonGuardRoutes("/", "/faq", "/login-sign-up")

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang="en" className="bg-white">
         <body>
            <StyledComponentsRegistry>
               <ConfigProvider theme={CustomAntTheme}>
                  <ReduxProvider>
                     <AuthProvider>
                        <RouteGuard nonGuardRoutes={nonGuardRoutes}>
                           <SocketProvider>
                              <AppLayoutProvider>{children}</AppLayoutProvider>
                           </SocketProvider>
                        </RouteGuard>
                     </AuthProvider>
                  </ReduxProvider>
               </ConfigProvider>
            </StyledComponentsRegistry>

            <Toaster
               position="bottom-left"
               reverseOrder={true}
               toastOptions={{
                  duration: 3000,
                  error: {
                     style: {
                        fontWeight: "bold",
                     },
                  },
                  success: {
                     style: {
                        fontWeight: "bold",
                     },
                  },
               }}
            />
         </body>
      </html>
   )
}
