export enum EInternalEvents {
   SCROLL_TO_BOTTOM_MSG_UI = "SCROLL_TO_BOTTOM_MSG:UI",
   SCROLL_TO_BOTTOM_MSG_ACTION = "SCROLL_TO_BOTTOM_MSG:ACTION",
   SCROLL_OUT_OF_BOTTOM = "SCROLL_OUT_OF_BOTTOM",
   LAST_FRIEND_REQUEST = "LAST_FRIEND_REQUEST",
   CLICK_ON_LAYOUT = "CLICK_ON_LAYOUT",
   MSG_TEXTFIELD_EDITED = "MSG_TEXTFIELD_EDITED",
}
