export enum EAuthStatus {
   UNKNOWN = "AUTH_STATUS_UNKNOWN",
   AUTHENTICATED = "AUTH_STATUS_AUTHENTICATED",
   UNAUTHENTICATED = "AUTH_STATUS_UNAUTHENTICATED",
}

export enum EPaginations {
   FRIEND_REQUESTS_PAGE_SIZE = 5,
   FRIENDS_PAGE_SIZE = 5,
   SEARCH_USERS_PAGE_SIZE = 20,
   DIRECT_MESSAGES_PAGE_SIZE = 20,
}

export enum EDirectChatErrMsgs {
   CONV_NOT_FOUND = "Direct Chat not found",
}

export enum EInvalidHttpErrMsgs {
   INVALID_REQUEST = "Invalid request",
}

export enum EEventNames {
   SCROLL_TO_BOTTOM_MSG_UI = "SCROLL_TO_BOTTOM_MSG:UI",
   SCROLL_TO_BOTTOM_MSG_ACTION = "SCROLL_TO_BOTTOM_MSG:ACTION",
   SCROLL_OUT_OF_BOTTOM = "SCROLL_OUT_OF_BOTTOM",
   LAST_FRIEND_REQUEST = "LAST_FRIEND_REQUEST",
}

export enum EServerErrMsgs {
   BAD_NETWORK_OR_ERROR = "Bad network or error from server.",
}

export enum ECustomHttpErrMsgs {
   SOMETHING_WENT_WRONG = "Something went wrong, please try again minutes later!",
}

export enum EFriendRequestStatus {
   PENDING = "PENDING",
   ACCEPTED = "ACCEPTED",
   REJECTED = "REJECTED",
}

export enum ETimeFormats {
   MMMM_DD_YYYY = "MMMM DD, YYYY",
   HH_mm = "HH:mm",
}

export enum ECommonStatus {
   SUCCESS = "success",
   FAIL = "fail",
   ERROR = "error",
}

export enum ESortTypes {
   ASC = "ASC",
   DESC = "DESC",
}

export enum HttpStatus {
   CONTINUE = 100,
   SWITCHING_PROTOCOLS = 101,
   PROCESSING = 102,
   EARLYHINTS = 103,
   OK = 200,
   CREATED = 201,
   ACCEPTED = 202,
   NON_AUTHORITATIVE_INFORMATION = 203,
   NO_CONTENT = 204,
   RESET_CONTENT = 205,
   PARTIAL_CONTENT = 206,
   AMBIGUOUS = 300,
   MOVED_PERMANENTLY = 301,
   FOUND = 302,
   SEE_OTHER = 303,
   NOT_MODIFIED = 304,
   TEMPORARY_REDIRECT = 307,
   PERMANENT_REDIRECT = 308,
   BAD_REQUEST = 400,
   UNAUTHORIZED = 401,
   PAYMENT_REQUIRED = 402,
   FORBIDDEN = 403,
   NOT_FOUND = 404,
   METHOD_NOT_ALLOWED = 405,
   NOT_ACCEPTABLE = 406,
   PROXY_AUTHENTICATION_REQUIRED = 407,
   REQUEST_TIMEOUT = 408,
   CONFLICT = 409,
   GONE = 410,
   LENGTH_REQUIRED = 411,
   PRECONDITION_FAILED = 412,
   PAYLOAD_TOO_LARGE = 413,
   URI_TOO_LONG = 414,
   UNSUPPORTED_MEDIA_TYPE = 415,
   REQUESTED_RANGE_NOT_SATISFIABLE = 416,
   EXPECTATION_FAILED = 417,
   I_AM_A_TEAPOT = 418,
   MISDIRECTED = 421,
   UNPROCESSABLE_ENTITY = 422,
   FAILED_DEPENDENCY = 424,
   PRECONDITION_REQUIRED = 428,
   TOO_MANY_REQUESTS = 429,
   INTERNAL_SERVER_ERROR = 500,
   NOT_IMPLEMENTED = 501,
   BAD_GATEWAY = 502,
   SERVICE_UNAVAILABLE = 503,
   GATEWAY_TIMEOUT = 504,
   HTTP_VERSION_NOT_SUPPORTED = 505,
}
